### ISSUE TITLE
the microphone's always recording

### ISSUE THREAD

**Issue by Wjxfi** [kolserdav/ana#81]
я думаю что это баг. Он должен записывать только когда я нажимаю на кнопку записи.

**Comment by kolserdav** [comment]
Приложение не записывает звук, браузер сигнализирует о том, что микрофон якобы используется несколько секунд при загрузке страницы, это связано с получением доступа к микрофону в данном методе https://github.com/kolserdav/ana/blob/bb17eff8b204307a064cd8285867a43658cd199f/packages/app/components/Translate.hooks.tsx#L795 Требуется доступ к микрофону для работы `webkitSpeechRecognition` по нажатию клавиши с изображением микрофона в нижмем правом углу поля для ввода текста.

**Comment by kolserdav** [comment]
Recording from a microphone in the application is not implemented at all, the `MediaStream` parameter is not even declared inside `getUserMedia.then((stream) => {})` in the web part. And there is no code related to the microphone API in the Android part at all.
The `SafeDot` application signals that this application has access to the microphone, and not that it is allegedly recording, but correctly assumes that if a recording can be made, then most likely it is being done, since in what it is the moment the application starts recording that `SafeDot` as a third-party service will not be able to identify.

Therefore, it is not possible to make a "record" point only when a key is pressed. Because after granting permission to use the microphone, this app will always have a dot for `SafeDot` until the permission to use the microphone is revoked from the app and the use of the microphone is disabled on first launch.
